{% set version = "21.11.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: poppler
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/poppler-{{ version }}.tar.xz
  sha256: 31b76b5cac0a48612fdd154c02d9eca01fd38fb8eaa77c1196840ecdeb53a584
  patches:
    - g-ir-scanner-libpath.patch
    - cmakelists.win.patch  # [win]
    - exportsymbols.patch  # [win]
    # system headers must be included before jpeg on Windows
    - includesystembeforejpeg.patch  # [win]
    - vs2015-no-for-loop-constexpr.win.patch  # [win]

build:
  skip: True  # [win]
  number: 0
  run_exports:
    # add new symbols often.  Don't remove symbols often at all.  Keeping default.
    #   https://abi-laboratory.pro/tracker/timeline/poppler/
    - {{ pin_subpackage('poppler') }}
  detect_binary_files_with_prefix: true
  skip: true  # [(unix and (cxx_compiler == 'toolchain_cxx'))]
  missing_dso_whitelist:
   - $RPATH/libm.so.6
   - $RPATH/libc.so.6
   - $RPATH/ld-linux-x86-64.so.2
   - $RPATH/libpthread.so.0
  ignore_run_exports:
   - libxcb

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [not win]
    - cmake
    - ninja
    - {{ posix }}patch
    - {{ posix }}make
    - perl
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - python >=3.6
    - boost-cpp
    - cairo  # [not win]
    - curl
    - freetype
    - glib
    - gobject-introspection 1.*  # [not win]
    - jpeg
    - libiconv                           # [osx]
    - libpng
    - libtiff
    - libxcb                             # [linux]
    - openjpeg >=2
    - zlib
    - fontconfig
    - libcurl
    - gettext  # [osx]
  run:
    - poppler-data
    - cairo  # [not win]
    - curl
    - freetype
    - glib
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - fontconfig
    - libcurl
    - zlib
    - gettext  # [osx]

test:
  commands:
    - pdfunite --help
    - pdftocairo --help  # [not win]

about:
  home: https://poppler.freedesktop.org/
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'The Poppler PDF manipulation library.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
