{% set version = "24.09.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set prefix = 'Library/' if win else '' %}

package:
  name: poppler-split
  version: {{ version }}

source:
  - url: https://gitlab.freedesktop.org/poppler/poppler/-/archive/poppler-{{ version }}/poppler-poppler-{{ version }}.tar.bz2
    sha256: dce88f84640b2a8592f7b9edbbefc563f584ef87fdf20359fa479367894f45df
    patches:                            # [win]
      - exportsymbols.patch             # [win]
      - windows-data.patch              # [win]
      - 0001-update-pc-file.patch       # [win]
      # libtiff uses Unix I/O even on Windows
      # https://github.com/conda-forge/libtiff-feedstock/pull/51
      - disable-libtiff-win32-io.patch  # [win]
      - includesystembeforejpeg.patch   # [win]
  - url: https://gitlab.freedesktop.org/poppler/test/-/archive/master/test-master.tar.bz2  # [not win]
    # This sha256 is always new.
    sha256: c8572344d9d52a6a7392b0f0882e610d2eafb35667335877473621227ec95216               # [not win]
    folder: test_suite                                                                     # [not win]

build:
  number: 4
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang-format 14.0.6  # [osx]
    # gobject-introspection 1.* requires setuptools at runtime, but
    # setuptools >= 65.0.0 is lacking the msvccompiler module in distutils.
    # https://github.com/pypa/setuptools/pull/3505
    - setuptools <65
    - binutils                           # [linux]
    - m2-msys2-runtime                   # [win]
    - m2-patch                           # [win]
    - {{ native }}pkg-config
    - cmake
    - {{ posix }}make
    - ninja
    - perl 5.*
    - gobject-introspection 1.78.*  # [not win]
  host:
    # Need python to run glib-mkenums.
    - python 3.12  # [win]
    # boost-python-devel is the new replacement for boost-cpp
    - libboost
    - libboost-python-devel
    - libboost-python
    - libboost-devel
    - libboost-headers
    - cairo {{ cairo }}
    - curl {{ libcurl }}
    - fontconfig {{ fontconfig }}
    - freetype {{ freetype }}
    - gettext {{ gettext }}  # [osx]
    - glib {{ glib }}
    - jpeg {{ jpeg }}
    - lcms2 {{ lcms2 }}
    - libcurl {{ libcurl }}
    - libiconv {{ libiconv }}
    - libpng {{ libpng }}
    - libtiff {{ libtiff }}
    - nss {{ nss }}  # [not win]
    - openjpeg {{ openjpeg }}
    - zlib {{ zlib }}
    # qtbase-devel is not available for osx-64
    - qtbase-devel 6  # [not (osx and x86_64)]

outputs:

{% set win_prefix = "" %}          # [not win]
{% set win_suffix = "" %}          # [not win]
{% set win_prefix = "Library/" %}  # [win]
{% set win_suffix = ".exe" %}      # [win]

  - name: poppler
    build:
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libc.so.6
        - $RPATH/ld-linux-x86-64.so.2
        - $RPATH/libpthread.so.0
        - $RPATH/ld64.so.1
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - libboost-python-devel
        - libboost-python
        - libboost-devel
        - libboost-headers
        - cairo {{ cairo }}
        - curl {{ libcurl }}
        - fontconfig {{ fontconfig }}  # [unix]
        - freetype {{ freetype }}
        - gettext {{ gettext }}  # [osx]
        - glib {{ glib }}
        - jpeg {{ jpeg }}
        - lcms2 {{ lcms2 }}
        - libcurl {{ libcurl }}
        - libiconv {{ libiconv }}
        - libpng {{ libpng }}
        - libtiff {{ libtiff }}
        - nss {{ nss }}    # [not win]
        - nspr {{ nspr }}  # [not win]
        - openjpeg {{ openjpeg }}
        - zlib {{ zlib }}
      run:
        - {{ pin_compatible('libboost-devel') }}
        - poppler-data
    files:
      - "Library/bin/poppler.dll"                      # [win]
      - "Library/bin/poppler-cpp.dll"                  # [win]
      - "Library/bin/poppler-glib.dll"                 # [win]
      - "{{ win_prefix }}bin/pdf*{{ win_suffix }}"
      - "{{ win_prefix }}include/poppler/*.h"
      - {{ win_prefix }}include/poppler/cpp
      - {{ win_prefix }}include/poppler/fofi
      - {{ win_prefix }}include/poppler/glib
      - {{ win_prefix }}include/poppler/goo
      - {{ win_prefix }}include/poppler/splash
      - "lib/girepository-1.0/Poppler-*.typelib"       # [not win]
      - "{{ win_prefix }}lib/*poppler.*"
      - "{{ win_prefix }}lib/*poppler-cpp.*"
      - "{{ win_prefix }}lib/*poppler-glib.*"
      - {{ win_prefix }}lib/pkgconfig/poppler.pc
      - {{ win_prefix }}lib/pkgconfig/poppler-cpp.pc
      - {{ win_prefix }}lib/pkgconfig/poppler-glib.pc
      - "share/gir-1.0/Poppler-*.gir"                  # [not win]
      - "{{ win_prefix }}share/man/man1/pdf*"
    test:
      commands:
        - pdfinfo -listenc
        - pdfunite --help
        - pdftocairo --help

  - name: poppler-qt
    build:
      skip: true  # [osx and x86_64]
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libc.so.6
        - $RPATH/ld-linux-x86-64.so.2
        - $RPATH/libpthread.so.0
        - $RPATH/poppler.dll
        - $RPATH/ld64.so.1
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('poppler', exact=True) }}
        # Only dependencies actually needed by poppler-qt
        - freetype {{ freetype }}
        - lcms2 {{ lcms2 }}
        - qtbase-devel 6
      run:
        - {{ pin_subpackage('poppler', exact=True) }}
    files:
      - Library/bin/poppler-qt6.dll  # [win]
      - {{ win_prefix }}include/poppler/qt6
      - "{{ win_prefix }}lib/*poppler-qt6.*"
      - {{ win_prefix }}lib/pkgconfig/poppler-qt6.pc
    test:
      commands:
        - test -f ${PREFIX}/lib/pkgconfig/poppler-qt6.pc  # [not win]
        - if not exist %LIBRARY_BIN%\\poppler.dll exit 1  # [win]

about:
  home: https://poppler.freedesktop.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: The Poppler PDF manipulation library.
  description: |
    Poppler is a PDF rendering library based on the xpdf-3.0 code base.
  doc_url: https://poppler.freedesktop.org
  dev_url: https://gitlab.freedesktop.org/poppler/poppler

extra:
  feedstock-name: poppler
  recipe-maintainers:
    - katietz
    - pkgw
    - ocefpaf
    - xhochy
    - xylar