{% set version = "0.77.0" %}

package:
  name: poppler
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/poppler-{{ version }}.tar.xz
  sha256: 7267eb4cbccd64a58244b8211603c1c1b6bf32c7f6a4ced2642865346102f36b
  patches:
    - g-ir-scanner-libpath.patch
    - cmakelists.win.patch  # [win]
    - exportsymbols.patch  # [win]
    # system headers must be included before jpeg on Windows
    - includesystembeforejpeg.patch  # [win]
    - vs2015-no-for-loop-constexpr.win.patch  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [(unix and (cxx_compiler == 'toolchain_cxx')) or (win and py27)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [not win]
    - cmake
    - perl
  host:
    - python 3.6
    - cairo  # [not win]
    - curl
    - freetype
    - glib
    - gobject-introspection 1.*  # [not win]
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib
  run:
    - poppler-data
    - cairo  # [not win]
    - curl
    - freetype
    - glib
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib

test:
  commands:
    - pdfunite --help
    - pdftocairo --help  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://poppler.freedesktop.org/
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'The Poppler PDF manipulation library.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
