{% set name = "poppler" %}
{% set version = "0.52.0" %}
{% set sha256 = "528b661738839f9a25f6e580fcd2d5db007e0a1948580c6489f0062798ca1992" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://poppler.freedesktop.org/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 3
  detect_binary_files_with_prefix: true
  skip: True  # [win or not py36]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - pkg-config  # [not win]
    - python
    - perl
    - cairo 1.14.*
    - curl
    - freetype
    - glib
    - gobject-introspection >=1.51,<2.0a0
    - jpeg
    - libpng
    - libtiff
    # - openjpeg 2.1.*
    - zlib
  run:
    - poppler-data
    - cairo 1.14.*
    - curl
    # - openjpeg 2.1.*

test:
  commands:
    - pdfunite --help
    - pdftocairo --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://poppler.freedesktop.org/
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'The Poppler PDF manipulation library.'

extra:
  recipe-maintainers:
    - pkgw
