{% set version = "0.67.0" %}

package:
  name: poppler
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/poppler-{{ version }}.tar.xz
  sha256: a34a4f1a0f5b610c584c65824e92e3ba3e08a89d8ab4622aee11b8ceea5366f9

build:
  number: 3
  detect_binary_files_with_prefix: true
  skip: true  # [win or not py36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [not win]
    - cmake 3.9.6
    - perl
  host:
    - python 3.6
    - cairo
    - curl
    - freetype
    - glib
    - gobject-introspection 1.55.*
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib
  run:
    - poppler-data
    - cairo
    - curl
    - freetype
    - glib
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib

test:
  commands:
    - pdfunite --help
    - pdftocairo --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://poppler.freedesktop.org/
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'The Poppler PDF manipulation library.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
