{% set name = "poppler" %}
{% set version = "0.62.0" %}
{% set sha256 = "5b9a73dfd4d6f61d165ada1e4f0abd2d420494bf9d0b1c15d0db3f7b83a729c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [win or not py36]

requirements:
  build:
    - pkg-config  # [not win]
    - cmake 3.9.6
    - toolchain
    - python
    - perl 5.22.2.1
    - cairo 1.14.*
    - curl >=7.44.0,<8
    - freetype 2.8.*
    - glib 2.55.*
    - gobject-introspection 1.55.*
    - jpeg 9*
    - libpng >=1.6.32,<1.6.35
    - libtiff >=4.0.8,<4.0.10
    - openjpeg 2.3.*
    - zlib 1.2.11
  run:
    - poppler-data
    - cairo 1.14.*
    - curl >=7.44.0,<8
    - freetype 2.8.*
    - glib 2.55.*
    - jpeg 9*
    - libpng >=1.6.32,<1.6.35
    - libtiff >=4.0.8,<4.0.10
    - openjpeg 2.3.*
    - zlib 1.2.11

test:
  commands:
    - pdfunite --help
    - pdftocairo --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://poppler.freedesktop.org/
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'The Poppler PDF manipulation library.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
