{% set name = "poppler" %}
{% set version = "0.66.0" %}
{% set sha256 = "2c096431adfb74bc2f53be466889b7646e1b599f28fa036094f3f7235cc9eae7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1
  detect_binary_files_with_prefix: true
  skip: true  # [win or not py36]

requirements:
  build:
    - pkg-config  # [not win]
    - cmake 3.9.6
    - perl 5.22.2.1
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cairo
    - curl
    - freetype
    - glib
    - gobject-introspection 1.55.*
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib
  run:
    - poppler-data
    - cairo
    - curl
    - freetype
    - glib
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib

test:
  commands:
    - pdfunite --help
    - pdftocairo --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://poppler.freedesktop.org/
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'The Poppler PDF manipulation library.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
