{% set name = "poppler" %}
{% set version = "0.61.1" %}
{% set sha256 = "1266096343f5163c1a585124e9a6d44474e1345de5cdfe55dc7b47357bcfcda9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1
  detect_binary_files_with_prefix: true
  skip: true  # [win or not py36]

requirements:
  build:
    - pkg-config  # [not win]
    - cmake 3.9.6
    - toolchain
    - python
    - perl 5.22.2.1
    - cairo 1.14.*
    - curl >=7.44.0,<8
    - freetype 2.7
    - glib 2.51.*
    - gobject-introspection 1.51.*
    - jpeg 9*
    - libpng >=1.6.22,<1.6.31
    - libtiff >=4.0.3,<4.0.8
    - openjpeg 2.1.*
    - zlib 1.2.11
  run:
    - poppler-data
    - cairo 1.14.*
    - curl >=7.44.0,<8
    - freetype 2.7
    - glib 2.51.*
    - jpeg 9*
    - libpng >=1.6.22,<1.6.31
    - libtiff >=4.0.3,<4.0.8
    - openjpeg 2.1.*
    - zlib 1.2.11

test:
  commands:
    - pdfunite --help
    - pdftocairo --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://poppler.freedesktop.org/
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'The Poppler PDF manipulation library.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
