travis:
  secure:
    BINSTAR_TOKEN: OgfOLNaCEDhinQfHLE0VR+sIsz3K6JwTl0da9xDaurt7fhdYiLeYpdaBlLbwtDMm5yIRYYjkXHcsnj0SF5tVwIvJhWhrwFCIEltytK66ErTy2KiTMW1HbJ6IDNiLRb5C5LqrlzCHLbieSilH2eqHxLI5zy3iit3fDiIBxNmVcwZxHntMOfcEd04+Ok4x+OP7Wm8F9KAEbe6oSQfy3Ztxbyv3uLmYmZLPiqwNt6N8PJV4G+1viM/KANHUs8g7zaAsh7p/s9PK2rMaxCMdSikN6DdR88T5mCTpobalHRuXLzJDpEKtNmeCA29UfgTXWIVohMG3XPwg5EF97UhnnsLAReNcre7wcAP2SRiLBujtSvvnlIQ0kVnE7giUKNZDklkpg7CLPEe8QsAK7V3c4namHjjCCRgeeWOMKxvrQX9mSI0lwGk4gcYtMYLGGTc2qvzeK9YnlRfd+iobP0k4C6DYSORLWX8X/d8r5Z1d7zmUoIupsAGiHq8CQXpUT4zLxbRuq3UNAZDtgRXixlz5ZlyjHVLRo0zvhAiLMR8dRuWdAW2TVaRxNqzTM9jGRtERUUanPYfCw1evdIHNAp7nhajiPxycEm7orL+hJSEJS45fNyf7QWFuc+xNMihVREGvCpe68wGiUJAsHz81zjKqpUZtOpO1JKQ2aCfD7DJh8538kHw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
