travis:
  secure:
    BINSTAR_TOKEN: 2uc5KK7WG3vaF8KCWn6aRETOrwKdfQDJfkiE1ZKJRqp8m5ygvASJYjq+W4QGsQ1cYyIaM8aEMI77RTaE/BLsEHBUEOJu7m+2t9l3i94NIsMPCtxlZQEgonqFraqaVTD0TnE9YK7erJLP6cJHrLech3OkXD+aRfaKa998UL7zbtIFQDjaj32MmPoikYSNJHSSLcOyTXHsmUxnnSn2Zu7AYtqaYXwroi3CfRtgb+svV7YkwjK85s7ycSswYC0Vd5Ljb3KuuyEqQO435gbeLvjEdrGtDGfTLGP1V+bAZgowd2DKChOlbF6XD925ezCXmB43DOupdOt96/hL5Daxa43PGCjh60K+C0vPGlXteHEAPFki2xgB89kjr7Af9/YzT1cH7LzmYQpvK2O2e/jKA+6A/ym4ClFGo92Zj72aY7TyZGRkunPVwZ/1P6vDPcn7VwaPZwuLg/W3swjAJUAgMn7rqhoSGwXC0tcr2jAmRwDKHgaiHZHaxzIyFlAjCpfC+2t0RXl+qEkVc2sgZorG0W9hpADJzJg+GQOuVgpp4CUxFFT2q6pXyqbWrRtryTcKz/H6dcAtfTxC0VE3+QGRTajVCtXLZxJl6v45jSRsr8zi/JZ/fMgkWukG99mio1Rb4dsa9syl4i4CZ8nm6lVFDGkhmpM925wK1fMNu2uXnhIcbIQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
